<?php

namespace app\index\model\b2b_tour;
use think\Exception;
use think\Model;
use think\Db;
class B2bTourDate extends Model{
    //protected $connection = ['database' => 'erp'];
    protected $table = 'b2b_tour_date';
    public function initialize()
    {
    	parent::initialize();
    
    }


    public function addB2bTourDate($params){

        $data['btb_tour_id'] = $params['btb_tour_id'];
        $data['arrival_date'] = $params['arrival_date'];
        $data['departure_date'] = $params['departure_date'];
        $data['session_type'] = $params['session_type'];
        $data['office_contact'] = $params['office_contact'];
        $data['note'] = $params['note'];
    	$data['status'] = $params['status'];

    	try{
    		Db::name('b2b_tour_date')->insert($data);
    	} catch (\Exception $e) {

            $result = $e->getMessage();
    		\think\Response::create(['code' => '400', 'msg' =>$result], 'json')->send();
    		exit();
    	}

    }

}